### ISSUE TITLE
missing grpc_cc.so file

### ISSUE THREAD

**Issue by turmeric-blend** [google-research/seed_rl#33]
hi, I have re-cloned this repo but couldn't run it as i noticed that the grpc_cc.so file is missing in grpc/ folder. I have tried to run build.sh in grpc/ folder but the grpc_cc.so file is still not generated. I have also tried to manually run the Dockerfile.grpc to no success. Below is the results when I run build.sh under grpc/ folder.

```
Sending build context to Docker daemon  62.98MB
Step 1/13 : FROM tensorflow/tensorflow:2.2.0-custom-op-gpu-ubuntu16 as grpc_compile
 ---> 4f52a8af55d1
Step 2/13 : RUN git clone https://github.com/tensorflow/custom-op.git
 ---> Using cache
 ---> ad802b5e9897
Step 3/13 : WORKDIR custom-op
 ---> Using cache
 ---> 4967ee6c88c8
Step 4/13 : RUN ./configure.sh
 ---> Using cache
 ---> f8fac4c15f9b
Step 5/13 : RUN echo '\nload("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")\n\nhttp_archive(\n    name = "com_github_grpc_grpc",\n    urls = [\n        "https://github.com/grpc/grpc/archive/ac1c5de1b36da4a1e3d72ca40b0e43f24266121a.tar.gz",\n    ],\n    strip_prefix = "grpc-ac1c5de1b36da4a1e3d72ca40b0e43f24266121a",\n)\n\nload("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")\ngrpc_deps()\nload("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")\ngrpc_extra_deps()' >> WORKSPACE
 ---> Using cache
 ---> 394cf60db842
Step 6/13 : ADD grpc/ grpc/
 ---> Using cache
 ---> fd6b4b6cc598
Step 7/13 : RUN bazel build grpc:ops/grpc.so grpc:service_py_proto --incompatible_remove_legacy_whole_archive=0
 ---> Using cache
 ---> a3adc0030562
Step 8/13 : ADD . /seed_rl
 ---> aa87974eefdc
Step 9/13 : RUN cp bazel-bin/grpc/ops/grpc.so /seed_rl/grpc/grpc_cc.so
 ---> Running in d12fd318a443
Removing intermediate container d12fd318a443
 ---> 0c4b868f40ba
Step 10/13 : RUN cp bazel-bin/grpc/service_pb2.py /seed_rl/grpc/service_pb2.py
 ---> Running in 83f66ec4890b
Removing intermediate container 83f66ec4890b
 ---> 4e7b53239638
Step 11/13 : WORKDIR /seed_rl/
 ---> Running in f5302466583e
Removing intermediate container f5302466583e
 ---> 7483220588ba
Step 12/13 : RUN pip3 install tensorflow-gpu==2.2.0
 ---> Running in 947cf84d0a86
Requirement already satisfied: tensorflow-gpu==2.2.0 in /usr/local/lib/python3.6/dist-packages (2.2.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.1.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.31.1)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.18.5)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.4.1)
Requirement already satisfied: tensorboard<2.3.0,>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (2.2.2)
Requirement already satisfied: google-pasta>=0.1.8 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (3.2.1)
Requirement already satisfied: astunparse==1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.6.3)
Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (3.12.2)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.9.0)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (2.10.0)
Requirement already satisfied: tensorflow-estimator<2.3.0,>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (2.2.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.29.0)
Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.12.1)
Requirement already satisfied: gast==0.3.3 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.3.3)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.12.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2.23.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (47.1.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.16.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2.6.8)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.6.0.post3)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.0.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (0.4.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2020.4.5.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2.9)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (4.1.0)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (3.1.0)
Removing intermediate container 947cf84d0a86
 ---> 9d8c39b44b09
Step 13/13 : RUN PYTHONPATH=/ python3 grpc/python/ops_test.py
 ---> Running in 6d6ca3fd49ac
Running tests under Python 3.6.10: /usr/bin/python3
[ RUN      ] OpsTest.test_batched_at_least_one_input
2020-07-12 04:33:10.707013: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-07-12 04:33:10.707035: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-12 04:33:10.707060: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2020-07-12 04:33:10.707468: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-12 04:33:10.737592: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2599990000 Hz
2020-07-12 04:33:10.738067: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ea02a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-12 04:33:10.738127: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[       OK ] OpsTest.test_batched_at_least_one_input
[ RUN      ] OpsTest.test_batched_first_dimension_must_match
[       OK ] OpsTest.test_batched_first_dimension_must_match
[ RUN      ] OpsTest.test_batched_inputs_at_least_rank1
[       OK ] OpsTest.test_batched_inputs_at_least_rank1
[ RUN      ] OpsTest.test_batched_output_is_batched
[       OK ] OpsTest.test_batched_output_is_batched
[ RUN      ] OpsTest.test_batched_outputs_at_least_rank1
[       OK ] OpsTest.test_batched_outputs_at_least_rank1
[ RUN      ] OpsTest.test_bind_multiple_functions([], False)
[       OK ] OpsTest.test_bind_multiple_functions([], False)
[ RUN      ] OpsTest.test_bind_multiple_functions([1], True)
[       OK ] OpsTest.test_bind_multiple_functions([1], True)
[ RUN      ] OpsTest.test_binding_function_twice
2020-07-12 04:33:11.447666: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:910 : Invalid argument: Function 'foo' was bound twice.
[       OK ] OpsTest.test_binding_function_twice
[ RUN      ] OpsTest.test_call_after_shutdown([], False)
2020-07-12 04:33:11.562585: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
[       OK ] OpsTest.test_call_after_shutdown([], False)
[ RUN      ] OpsTest.test_call_after_shutdown([1], True)
2020-07-12 04:33:11.607132: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
[       OK ] OpsTest.test_call_after_shutdown([1], True)
[ RUN      ] OpsTest.test_call_after_shutdown_and_start([], False)
[       OK ] OpsTest.test_call_after_shutdown_and_start([], False)
[ RUN      ] OpsTest.test_call_after_shutdown_and_start([1], True)
[       OK ] OpsTest.test_call_after_shutdown_and_start([1], True)
[ RUN      ] OpsTest.test_client_non_scalar_server_address
[       OK ] OpsTest.test_client_non_scalar_server_address
[ RUN      ] OpsTest.test_create_variable([], False)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0712 04:33:12.043102 140415275980544 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[       OK ] OpsTest.test_create_variable([], False)
[ RUN      ] OpsTest.test_create_variable([1], True)
[       OK ] OpsTest.test_create_variable([1], True)
[ RUN      ] OpsTest.test_deletion_while_in_blocking_call([], False)
2020-07-12 04:33:12.344345: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
2020-07-12 04:33:12.374135: W tensorflow/core/kernels/queue_base.cc:277] 283: Skipping cancelled enqueue attempt with queue not closed
[       OK ] OpsTest.test_deletion_while_in_blocking_call([], False)
[ RUN      ] OpsTest.test_deletion_while_in_blocking_call([1], True)
2020-07-12 04:33:12.418763: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
2020-07-12 04:33:12.447515: W tensorflow/core/kernels/queue_base.cc:277] 299: Skipping cancelled enqueue attempt with queue not closed
[       OK ] OpsTest.test_deletion_while_in_blocking_call([1], True)
[ RUN      ] OpsTest.test_empty_input
[       OK ] OpsTest.test_empty_input
[ RUN      ] OpsTest.test_empty_output([], False)
[       OK ] OpsTest.test_empty_output([], False)
[ RUN      ] OpsTest.test_empty_output([1], True)
[       OK ] OpsTest.test_empty_output([1], True)
[ RUN      ] OpsTest.test_failing_function([], False)
[       OK ] OpsTest.test_failing_function([], False)
[ RUN      ] OpsTest.test_failing_function([1], True)
[       OK ] OpsTest.test_failing_function([1], True)
[ RUN      ] OpsTest.test_invalid_number_of_arguments([], False)
[       OK ] OpsTest.test_invalid_number_of_arguments([], False)
[ RUN      ] OpsTest.test_invalid_number_of_arguments([1], True)
[       OK ] OpsTest.test_invalid_number_of_arguments([1], True)
[ RUN      ] OpsTest.test_invalid_shape([], False)
[       OK ] OpsTest.test_invalid_shape([], False)
[ RUN      ] OpsTest.test_invalid_shape([1], True)
[       OK ] OpsTest.test_invalid_shape([1], True)
[ RUN      ] OpsTest.test_invalid_type([], False)
[       OK ] OpsTest.test_invalid_type([], False)
[ RUN      ] OpsTest.test_invalid_type([1], True)
[       OK ] OpsTest.test_invalid_type([1], True)
[ RUN      ] OpsTest.test_large_tensor([], False)
[       OK ] OpsTest.test_large_tensor([], False)
[ RUN      ] OpsTest.test_large_tensor([1], True)
[       OK ] OpsTest.test_large_tensor([1], True)
[ RUN      ] OpsTest.test_nests([], False)
[       OK ] OpsTest.test_nests([], False)
[ RUN      ] OpsTest.test_nests([1], True)
[       OK ] OpsTest.test_nests([1], True)
[ RUN      ] OpsTest.test_no_output([], False)
[       OK ] OpsTest.test_no_output([], False)
[ RUN      ] OpsTest.test_no_output([1], True)
[       OK ] OpsTest.test_no_output([1], True)
[ RUN      ] OpsTest.test_not_bound
2020-07-12 04:33:14.916092: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:936 : Unavailable: No function was bound
[       OK ] OpsTest.test_not_bound
[ RUN      ] OpsTest.test_not_fully_specified_outputs
[       OK ] OpsTest.test_not_fully_specified_outputs
[ RUN      ] OpsTest.test_not_fully_specified_outputs2
[       OK ] OpsTest.test_not_fully_specified_outputs2
[ RUN      ] OpsTest.test_queue([], False)
[       OK ] OpsTest.test_queue([], False)
[ RUN      ] OpsTest.test_queue([1], True)
[       OK ] OpsTest.test_queue([1], True)
[ RUN      ] OpsTest.test_server_non_vector_server_addresses
[       OK ] OpsTest.test_server_non_vector_server_addresses
[ RUN      ] OpsTest.test_session
[  SKIPPED ] OpsTest.test_session
[ RUN      ] OpsTest.test_shutdown_waiting_for_full_batch
2020-07-12 04:33:16.670570: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
[       OK ] OpsTest.test_shutdown_waiting_for_full_batch
[ RUN      ] OpsTest.test_shutdown_while_in_blocking_call([], False)
2020-07-12 04:33:16.833345: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
2020-07-12 04:33:16.860401: W tensorflow/core/kernels/queue_base.cc:277] 734: Skipping cancelled enqueue attempt with queue not closed
[       OK ] OpsTest.test_shutdown_while_in_blocking_call([], False)
[ RUN      ] OpsTest.test_shutdown_while_in_blocking_call([1], True)
2020-07-12 04:33:16.890666: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
2020-07-12 04:33:16.918619: W tensorflow/core/kernels/queue_base.cc:277] 750: Skipping cancelled enqueue attempt with queue not closed
[       OK ] OpsTest.test_shutdown_while_in_blocking_call([1], True)
[ RUN      ] OpsTest.test_shutdown_while_in_call([], False)
2020-07-12 04:33:17.063580: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
[       OK ] OpsTest.test_shutdown_while_in_call([], False)
[ RUN      ] OpsTest.test_shutdown_while_in_call([1], True)
2020-07-12 04:33:18.112495: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
[       OK ] OpsTest.test_shutdown_while_in_call([1], True)
[ RUN      ] OpsTest.test_simple([], False)
[       OK ] OpsTest.test_simple([], False)
[ RUN      ] OpsTest.test_simple([1], True)
[       OK ] OpsTest.test_simple([1], True)
[ RUN      ] OpsTest.test_simple_two_calls([], False)
[       OK ] OpsTest.test_simple_two_calls([], False)
[ RUN      ] OpsTest.test_simple_two_calls([1], True)
[       OK ] OpsTest.test_simple_two_calls([1], True)
[ RUN      ] OpsTest.test_starting_twice
2020-07-12 04:33:19.578631: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:936 : Invalid argument: Server is already started
[       OK ] OpsTest.test_starting_twice
[ RUN      ] OpsTest.test_stress_test
2020-07-12 04:34:02.588852: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
2020-07-12 04:34:02.588852: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
2020-07-12 04:34:02.589077: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
2020-07-12 04:34:02.589125: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at grpc.cc:1091 : Unavailable: Read failed, is the server closed?
[       OK ] OpsTest.test_stress_test
[ RUN      ] OpsTest.test_string([], False)
[       OK ] OpsTest.test_string([], False)
[ RUN      ] OpsTest.test_string([1], True)
[       OK ] OpsTest.test_string([1], True)
[ RUN      ] OpsTest.test_tpu([], False)
[       OK ] OpsTest.test_tpu([], False)
[ RUN      ] OpsTest.test_tpu([1], True)
[       OK ] OpsTest.test_tpu([1], True)
[ RUN      ] OpsTest.test_tpu_tf_function_same_device([], False)
[       OK ] OpsTest.test_tpu_tf_function_same_device([], False)
[ RUN      ] OpsTest.test_tpu_tf_function_same_device([1], True)
[       OK ] OpsTest.test_tpu_tf_function_same_device([1], True)
[ RUN      ] OpsTest.test_two_clients([], False)
[       OK ] OpsTest.test_two_clients([], False)
[ RUN      ] OpsTest.test_two_clients([1], True)
[       OK ] OpsTest.test_two_clients([1], True)
[ RUN      ] OpsTest.test_two_clients([2], True)
[       OK ] OpsTest.test_two_clients([2], True)
[ RUN      ] OpsTest.test_upvalue([], False)
[       OK ] OpsTest.test_upvalue([], False)
[ RUN      ] OpsTest.test_upvalue([1], True)
[       OK ] OpsTest.test_upvalue([1], True)
[ RUN      ] OpsTest.test_variable_out_of_scope
[       OK ] OpsTest.test_variable_out_of_scope
[ RUN      ] OpsTest.test_wait_for_server([], False)
[       OK ] OpsTest.test_wait_for_server([], False)
[ RUN      ] OpsTest.test_wait_for_server([1], True)
[       OK ] OpsTest.test_wait_for_server([1], True)
[ RUN      ] OpsTest.test_wait_for_server2([], False)
[       OK ] OpsTest.test_wait_for_server2([], False)
[ RUN      ] OpsTest.test_wait_for_server2([1], True)
[       OK ] OpsTest.test_wait_for_server2([1], True)
----------------------------------------------------------------------
Ran 68 tests in 77.762s

OK (skipped=1)
Removing intermediate container 6d6ca3fd49ac
 ---> 5c08b5cda234
Successfully built 5c08b5cda234
Successfully tagged seed_rl:grpc
74c84f964c08b3ec22a99c5db5097ced837b3cd36ade69af47b00080594608cc

```

**Comment by lespeholt** [comment]
Fixing it asap. The .so can be found in the history.

What you did is actually correct. The only thing missing is that you copy the .so from the docker, like
docker cp [id of container]:/seed_rl/grpc/grpc_cc.so [local path]/grpc_cc.so

**Comment by mjsML** [comment]
same issue here ... I even tried to do a local build instead of pulling the docker image of custom_op but it failed due to local variables on where the tf libs are installed :(

**Comment by mjsML** [comment]
> grpc

@lespeholt maybe share the commit ID where it was available? I tried to search manually with no luck :(

**Comment by lespeholt** [comment]
The issue should be fixed in 2-3 hours :-)

**Comment by mjsML** [comment]
@lespeholt I added this
`docker cp $id:/seed_rl/grpc/grpc_cc.so ~/seed_rl/grpc/grpc_cc.so`
 [here](https://github.com/google-research/seed_rl/blob/f3a08a1f813ed71e1606c371fde5efcc2874b213/grpc/build.sh#L27)
and that copied the file as docker finished the build ... hope that helps :)

**Comment by mjsML** [comment]
Still blows up tho if I just copy the .so file :( 

`2020-07-13 15:02:19.692225: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
I0713 15:02:21.512532 139812448827264 actor.py:55] Starting actor loop
2020-07-13 15:02:21.514190: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-13 15:02:21.516809: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:21.517389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2020-07-13 15:02:21.517439: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 15:02:21.519046: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 15:02:21.520686: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-13 15:02:21.521021: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-13 15:02:21.522546: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-13 15:02:21.523676: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-13 15:02:21.527441: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 15:02:21.527584: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:21.528158: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:21.528633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-13 15:02:21.534356: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200000000 Hz
2020-07-13 15:02:21.534637: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1514d80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-13 15:02:21.534671: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-13 15:02:21.623585: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:21.624262: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1514f40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-13 15:02:21.624304: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-07-13 15:02:21.624487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:21.625054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2020-07-13 15:02:21.625089: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 15:02:21.625127: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 15:02:21.625141: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-13 15:02:21.625154: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-13 15:02:21.625168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-13 15:02:21.625181: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-13 15:02:21.625195: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 15:02:21.625250: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:21.625720: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:21.626216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-13 15:02:21.626258: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 15:02:22.157773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-13 15:02:22.157836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-07-13 15:02:22.157847: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-07-13 15:02:22.158056: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:22.158644: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 15:02:22.159105: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-07-13 15:02:22.159140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11176 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
I0713 15:02:22.163368 139812448827264 env.py:43] Creating environment: Pong
Traceback (most recent call last):
  File "/content/seed_rl/atari/r2d2_main.py", line 69, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/seed_rl/atari/r2d2_main.py", line 59, in main
    actor.actor_loop(env.create_environment)
  File "/content/seed_rl/atari/../../seed_rl/common/actor.py", line 97, in actor_loop
    FLAGS.task, run_id, env_output, raw_reward)
  File "/content/seed_rl/atari/../../seed_rl/grpc/python/ops.py", line 153, in call
    Toutput_list=flat_output_dtypes)
  File "<string>", line 610, in grpc_client_call
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_inference_3738}} [_Derived_]{{function_node __inference_append_3325}} {{function_node __inference_append_3325}} assertion failed: [Duplicate actor ids] [Condition x == y did not hold element-wise:] [x (UnrollStore/Shape:0) = ] [2] [y (UnrollStore/Shape_1:0) = ] [1]
	 [[{{node UnrollStore/assert_equal_1/Assert/Assert}}]]
	 [[StatefulPartitionedCall_1]] [Op:GrpcClientCall]`

**Comment by lespeholt** [comment]
Should have been fixed now :-)
