### ISSUE TITLE
Cannot assign a device for operation Aggregator/Gather

### ISSUE THREAD

**Issue by brieyla1** [google-research/seed_rl#43]
the TF 2.3 update broke something on the learner side.

here is the error
```
2020-09-14 14:52:29.201093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:0 with 10605 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2020-09-14 14:52:29.668067: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at grpc.cc:927 : Invalid argument: Cannot assign a device for operation Aggregator/Gather: Could not satisfy explicit device specification '' because the node {{colocation_node Aggregator/Gather}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:GPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=2 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceScatterUpdate: CPU XLA_CPU XLA_GPU 
_Arg: GPU CPU XLA_CPU XLA_GPU 
ResourceGather: GPU CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  aggregator_gather_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  Aggregator/Gather (ResourceGather) 
  Aggregator/ResourceScatterUpdate (ResourceScatterUpdate) 

         [[{{node Aggregator/Gather}}]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "../football/vtrace_main.py", line 55, in main
    create_optimizer)
  File "/seed_rl/agents/vtrace/learner.py", line 423, in learner_loop
    create_host(i, host, inference_devices)
  File "/seed_rl/agents/vtrace/learner.py", line 417, in create_host
    server.bind([create_inference_fn(d) for d in inference_devices])
  File "/seed_rl/grpc/python/ops.py", line 109, in bind
    output_specs=output_specs_proto.SerializeToString())
  File "<string>", line 212, in grpc_server_bind
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation Aggregator/Gather: Could not satisfy explicit device specification '' because the node {{colocation_node Aggregator/Gather}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:GPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=2 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceScatterUpdate: CPU XLA_CPU XLA_GPU 
_Arg: GPU CPU XLA_CPU XLA_GPU 
ResourceGather: GPU CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  aggregator_gather_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  Aggregator/Gather (ResourceGather) 
  Aggregator/ResourceScatterUpdate (ResourceScatterUpdate) 

         [[{{node Aggregator/Gather}}]] [Op:GrpcServerBind]

```

Environment:

OS: test Ubuntu 20 and debian 9
Machine types: GCP 8 cpu 30G ram
GPU: tested NVIDIA Tesla K80, NVIDIA Tesla V100, and T4

docker version
```
lancelot@seed-k80:~/seed_rl$ docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:20 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    31W / 149W |     14MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1071      G   /usr/lib/xorg/Xorg                             8MiB |
|    0      1404      G   /usr/bin/gnome-shell                           3MiB |
+-----------------------------------------------------------------------------+
```

command line:
`./run_local.sh football vtrace 4`

it seems the Server.bind is forced to use a GPU when the code only allows for a CPU. the error says: 
`assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]`

grpc.cc:893
```
    Device* cpu_device;
    OP_REQUIRES_OK(ctx, lib->device_mgr()->LookupDevice("CPU:0", &cpu_device));
    int num_args = fdef->signature().input_arg_size();
```

**Comment by lespeholt** [comment]
Thanks for reporting this. Those operations shouldn't end up on the GPU.

**Comment by lespeholt** [comment]
I believe I have located the error and will submit a patch.

**Comment by lespeholt** [comment]
This should be fixed now :)
